In [ ]:
import numpy as np
from scipy.optimize import minimize
from math import sqrt
import pickle

<h2>Given, nothing to do</h2>

In [ ]:
def initializeWeights(n_in, n_out):
    '''
    initializeWeights return the random weights for Neural Network given the
    number of node in the input layer and output layer

    Input:
    n_in: number of nodes of the input layer
    n_out: number of nodes of the output layer

    Output:
    W: matrix of random initial weights with size (n_out x (n_in + 1))
    '''
    epsilon = sqrt(6) / sqrt(n_in + n_out + 1)
    W = (np.random.rand(n_out, n_in + 1) * 2 * epsilon) - epsilon
    return W

In [ ]:
def preprocess(filename,scale=True):
#     print("preprocess")
    '''
     Input:
     filename: pickle file containing the data_size
     scale: scale data to [0,1] (default = True)
     Output:
     train_data: matrix of training set. Each row of train_data contains
       feature vector of a image
     train_label: vector of label corresponding to each image in the training
       set
     test_data: matrix of training set. Each row of test_data contains
       feature vector of a image
     test_label: vector of label corresponding to each image in the testing
       set
    '''
    with open(filename, 'rb') as f:
        train_data = pickle.load(f)
        train_label = pickle.load(f)
        test_data = pickle.load(f)
        test_label = pickle.load(f)
    # convert data to double
    train_data = train_data.astype(float)
    test_data = test_data.astype(float)

    # scale data to [0,1]
    if scale:
        train_data = train_data/255
        test_data = test_data/255

    return train_data, train_label, test_data, test_label

<h2>TO DO</h2>

In [ ]:
def sigmoid(z):
    '''
    Notice that z can be a scalar, a vector or a matrix
    return the sigmoid of input z (same dimensions as z)
    '''
#     print("sigmoid")
    # your code here - remove the next four lines
    if np.isscalar(z):
        s = 1 / (1 + np.exp(-z))
    else:
        s = np.zeros(z.shape)
#         for i in range(1,z.shape[0]):
        for i in range(1,100):
            for j in range(1,z.shape[1]):
                s[i][j] = 1 / (1 + np.exp(-z[i][j]))
    return s

In [ ]:
def ji():
    

In [ ]:
def nnObjFunction(params, *args):
#     print("nnObjFunction")
    '''
    % nnObjFunction computes the value of objective function (cross-entropy
    % with regularization) given the weights and the training data and lambda
    % - regularization hyper-parameter.

    % Input:
    % params: vector of weights of 2 matrices W1 (weights of connections from
    %     input layer to hidden layer) and W2 (weights of connections from
    %     hidden layer to output layer) where all of the weights are contained
    %     in a single vector.
    % n_input: number of node in input layer (not including the bias node)
    % n_hidden: number of node in hidden layer (not including the bias node)
    % n_class: number of node in output layer (number of classes in
    %     classification problem
    % train_data: matrix of training data. Each row of this matrix
    %     represents the feature vector of a particular image
    % train_label: the vector of truth label of training images. Each entry
    %     in the vector represents the truth label of its corresponding image.
    % lambda: regularization hyper-parameter. This value is used for fixing the
    %     overfitting problem.

    % Output:
    % obj_val: a scalar value representing value of error function
    % obj_grad: a SINGLE vector (not a matrix) of gradient value of error function
    % NOTE: how to compute obj_grad
    % Use backpropagation algorithm to compute the gradient of error function
    % for each weights in weight matrices.
    '''
    n_input, n_hidden, n_class, train_data, train_label, lambdaval = args
    # First reshape 'params' vector into 2 matrices of weights W1 and W2

    W1 = params[0:n_hidden * (n_input + 1)].reshape((n_hidden, (n_input + 1)))
    W2 = params[(n_hidden * (n_input + 1)):].reshape((n_class, (n_hidden + 1)))
    obj_val = 0

    # ----- FEEDFORWARD -----
    # HIDDEN UNIT
    # n_hidden     # num of hidden features = 50
    data = train_data.shape[0]
    d = train_data.shape[1]
    # train_data.shape[0] = 60,000
    # train_data.shape[1] = 784
    
    
#     a = np.zeros((data, n_hidden))
    a = np.zeros((100,n_hidden))
    sum = 0
#     for i in range(1,data):
    for i in range(1,100):
        for j in range(1,n_hidden):
            for p in range(1,d):
                sum += W1[j][p] * train_data[i][p]
            a[i][j] = sum
    
    z = sigmoid(a)
    print(z.shape)
    print(z)
    
    
    # OUTPUT UNITS
#     b = np.zeros((data, n_class))
    b = np.zeros((100,n_class))
    sum = 0
#     for i in range(1,data):
    for i in range(1,100):
        for l in range(1,n_class):
            for j in range(1,n_hidden):
                sum += W2[l][j]*z[i][j]
            b[i][l] = sum
    
    o = sigmoid(b)
    print(o.shape)
    print(o)
    

    # ----- FIND obj_val (using equation (5)) -----
#     y = train_label
    sum = 0
#     for n in range(1,data):
    for i in range(1, 100):
        for l in range(1,n_class):
            sum += (train_label[i] * np.log(o[i][l]) + \
                    (1 - train_label[i]) * np.log(1 - o[i][l]))
    
    obj_val = (sum * (-1 / data))
    print("obj_val")
    print(obj_val)
    
    
    
    # ----- FIND obj_grad (using equations (16) & (17)) -----
    obj_grad = np.zeros(params.shape)
    # (16)




    # Make sure you reshape the gradient matrices to a 1D array. for instance if
    # your gradient matrices are grad_W1 and grad_W2
    # you would use code similar to the one below to create a flat array
    # obj_grad = np.concatenate((grad_W1.flatten(), grad_W2.flatten()),0)

    return (obj_val, obj_grad)

In [ ]:
def nnPredict(W1, W2, data):
    '''
    % nnPredict predicts the label of data given the parameter W1, W2 of Neural
    % Network.

    % Input:
    % W1: matrix of weights for hidden layer units
    % W2: matrix of weights for output layer units
    % data: matrix of data. Each row of this matrix represents the feature
    %       vector of a particular image

    % Output:
    % label: a column vector of predicted labels
    '''

    labels = np.zeros((data.shape[0],))
    # Your code here

    return labels

<h2>nnScript.py</h2>

In [ ]:
'''
Neural Network Script Starts here
'''
# from nnFunctions import *
# you may experiment with a small data set (mnist_sample.pickle) first
filename = 'mnist_all.pickle'
#filename = 'AI_quick_draw.pickle'
train_data, train_label, test_data, test_label = preprocess(filename)

#  Train Neural Network
# set the number of nodes in input unit (not including bias unit)
n_input = train_data.shape[1]

# set the number of nodes in hidden unit (not including bias unit)
n_hidden = 50

# set the number of nodes in output unit
n_class = 10

# initialize the weights into some random matrices
initial_W1 = initializeWeights(n_input, n_hidden)
initial_W2 = initializeWeights(n_hidden, n_class)

# unroll 2 weight matrices into single column vector
initialWeights = np.concatenate((initial_W1.flatten(), initial_W2.flatten()), 0)

# set the regularization hyper-parameter
lambdaval = 0

args = (n_input, n_hidden, n_class, train_data, train_label, lambdaval)

# Train Neural Network using fmin_cg or minimize from scipy,optimize module. Check documentation for a working example
opts = {'maxiter': 50}  # Preferred value.

nn_params = minimize(nnObjFunction, initialWeights, jac=True, args=args, method='CG', options=opts)

# Reshape nnParams from 1D vector into W1 and W2 matrices
W1 = nn_params.x[0:n_hidden * (n_input + 1)].reshape((n_hidden, (n_input + 1)))
W2 = nn_params.x[(n_hidden * (n_input + 1)):].reshape((n_class, (n_hidden + 1)))
print("training done!")

# Test the computed parameters

# find the accuracy on Training Dataset
predicted_label = nnPredict(W1, W2, train_data)
print('\n Training set Accuracy:' + str(100 * np.mean((predicted_label == train_label).astype(float))) + '%')

# find the accuracy on Testing Dataset
predicted_label = nnPredict(W1, W2, test_data)
print('\n Test set Accuracy:    ' + str(100 * np.mean((predicted_label == test_label).astype(float))) + '%')


<h2>Sample data to test your nnObjFunction() [from Piazza]</h2>

In [200]:


# Paste your sigmoid function here
def testsig(z):
    if np.isscalar(z):
        s = 1 / (1 + np.exp(-z))
    else:
        s = np.zeros(z.shape)
        for i in range(0,z.shape[0]):
            for j in range(0,z.shape[1]):
                s[i][j] = 1 / (1 + np.exp(-z[i][j]))
    return s

# Paste your nnObjFunction here
def testnnObjFunction(params, *args):
    W1 = params[0:n_hidden * (n_input + 1)].reshape((n_hidden, (n_input + 1)))
    W2 = params[(n_hidden * (n_input + 1)):].reshape((n_class, (n_hidden + 1)))
    obj_val = 0
    
#     print("data")
#     print(training_data)
#     print("W1")
#     print(W1)

#     print(training_data.shape)
#     print(training_data)
#     print(W1.shape)
#     print(W2.shape)

#     print("label")
#     print(training_label.shape)
#     print(training_label)
    
    # ----- FEEDFORWARD -----
    # HIDDEN UNIT
    # n_hidden     # num of hidden features = 50
    data = training_data.shape[0]
    d = training_data.shape[1]
    # train_data.shape[0] = 60,000
    # train_data.shape[1] = 784
    
    
    a = np.zeros((data, n_hidden))
    sum = 0
    for i in range(0,data):
        for j in range(0,n_hidden):
            for p in range(0,d+1):
                if p == d:
                    sum += W1[j][p] * 1       # <--- using this as bias for input
                else:
                    sum += W1[j][p] * training_data[i][p]
                    
            a[i][j] = sum
            sum = 0
    
#     print("a")
#     print(a.shape)
#     print(a)
    z = testsig(a)
    print("z")
    print(z.shape)
#     print(z)
    ones = np.ones((z.shape[0],1))
    z = np.append(z,ones,axis=1)           # <--- adds bias to z
#     print("z with bias")
#     print(z.shape)
    print(z)
    
#     print("W2")
#     print(W2.shape)
#     print(W2)
    
    
    # OUTPUT UNITS
    b = np.zeros((data, n_class))
    sum = 0
    for i in range(0,data):
        for l in range(0,n_class):
            for j in range(0,n_hidden+1):
                sum += W2[l][j] * z[i][j]
            b[i][l] = sum
            sum = 0
            
#     print("b")
#     print(b.shape)
#     print(b)
    
    o = testsig(b)
    print("o")
    print(o.shape)
    print(o)
    

    # ----- FIND obj_val (using equation (5)) -----
#     y = train_label
    sum = 0
    for i in range(0,data):
        for l in range(0,n_class):
            sum += (training_label[i] * np.log(o[i][l]) + \
                    (1 - training_label[i]) * np.log(1 - o[i][l]))
#             print(sum)
    
    obj_val = (sum * (-1 / data))
    
    obj_grad = np.zeros(params.shape)

    return (obj_val, obj_grad)


n_input = 5
n_hidden = 3
n_class = 2
training_data = np.array([np.linspace(0,1,num=5),np.linspace(1,0,num=5)])
training_label = np.array([0,1])
lambdaval = 0
params = np.linspace(-5,5, num=26)
args = (n_input, n_hidden, n_class, training_data, training_label, lambdaval)
objval,objgrad = testnnObjFunction(params, *args)
print("Objective value:")
print(objval)
print("Gradient values: ")
print(objgrad)
print(8.00656672137799-7.87167506597)

z
(2, 3)
[[3.72663928e-06 1.63024994e-02 9.86613082e-01 1.00000000e+00]
 [5.04347408e-07 2.23784852e-03 9.08877039e-01 1.00000000e+00]]
o
(2, 2)
[[0.99834489 0.99993274]
 [0.99783345 0.99989798]]
Objective value:
8.00656672137799
Gradient values: 
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0.]
0.13489165540798975
